from __future__ import print_function
import os

from leapp.actors import Actor
from leapp.tags import FirstBootPhaseTag, IPUWorkflowTag
from leapp.libraries.common.cllaunch import run_on_cloudlinux

REPO_DIR = '/etc/yum.repos.d'
LEAPP_COPY_SUFFIX = "_leapp_custom.repo"


class CleanupLeappGeneratedRepofiles(Actor):
    """
    Remove custom repository files generated by Leapp for the upgrade.
    """

    name = 'cleanup_leapp_generated_repofiles'
    consumes = ()
    produces = ()
    tags = (FirstBootPhaseTag, IPUWorkflowTag)

    @run_on_cloudlinux
    def process(self):
        for repofile_full in os.listdir(REPO_DIR):
            if repofile_full.endswith(LEAPP_COPY_SUFFIX):
                full_repo_path = os.path.join(REPO_DIR, repofile_full)
                os.unlink(full_repo_path)
